### ISSUE TITLE
[PE-D][Tester A] No command to view reminder for items

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-1/tp#104]
![image.png](https://raw.githubusercontent.com/Cyrus-Krispin/ped/main/files/a82b7666-7162-4596-9b47-419e0ef0398a.png)

---------------------------------------------
While getting reminder for items when the app is launched is a neat feature, users preferably want to view these reminders at any point in time. No command available to view these reminders again.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Cyrus-Krispin/ped#3

**Comment by Tariq-droid** [comment]
we cannot fix feature flaws in v1.4

**Comment by tingyic** [comment]
Reopening this issue, because we can propose a solution in the DG now.

**Comment by jayhee3** [comment]
> Reopening this issue, because we can propose a solution in the DG now.

Can you add it to the Planned Enhancements" section of the DG?

**Comment by jayhee3** [comment]
Fixed. Added to 'Coming soon' section of UG, and will add to future enhancements in DG

**Comment by Tariq-droid** [comment]
finished with PR #168
