### ISSUE TITLE
[PE-D][Tester D] sort command produces unexpected order

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-1/tp#114]
### Description
When sorting by timeslot, the order appears incorrect.

### Steps for reproducing
Assuming that the provided sample data is used, enter the command: `sort timeslot`

### Expected output
GEA1000 to appear last as Sunday is the first day of the week and Saturday is the last.

### Actual output
GEA1000 appears first.

### Other details
Not sure if this was the intended behaviour. Perhaps, the intention was that Saturday be treated as the first day of the week. In that case, it might be good to specify it in the user guide so as to avoid confusion. 

### Screenshot

![image.png](https://raw.githubusercontent.com/hingen/ped/main/files/192a3452-285d-47ec-bd5b-656fa39652fb.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: hingen/ped#7

**Comment by jayhee3** [comment]
Fixed. Documented in the UG.
