### ISSUE TITLE
[PE-D][Tester A] Command summary does not show all available commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-1/tp#116]
**Command summary**

![image.png](https://raw.githubusercontent.com/Cyrus-Krispin/ped/main/files/cff9d5ae-a646-42eb-9674-00309a62905e.png)

----------------------------------------------------------

**Actual list of features**

![image.png](https://raw.githubusercontent.com/Cyrus-Krispin/ped/main/files/d50fd28a-c2a8-4242-acc9-08e3897a6848.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Cyrus-Krispin/ped#6

**Comment by jamieeeleow** [comment]
Covered in issue #126
