### ISSUE TITLE
[PE-D][Tester D] Timeslot allows start time to be after end time

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-1/tp#125]
### Description
The `edit` command allows time slots to be specified such that the end time is before the start time.

### Steps for reproducing
Assuming sample data is used, execute the command: `edit 1 e/Saturday 23:59 09:00`

### Expected output
An error message informing me that the start time is after the end time.

### Actual output
The command is accepted.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: hingen/ped#10

**Comment by jayhee3** [comment]
Fixed by adding an extra check.
