### ISSUE TITLE
[PE-D][Tester D] Add command does not restrict tag to Lecture, Tutorial, and Lab

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-1/tp#127]
### Description
Base on the invalid command format of the `add` command, one would assume that the tag should be restricted to `Lecture`, `Tutorial`, or `Lab`. However, other tags are also accepted.

### Steps for reproducing
Assuming the sample data is used, execute the command: `add n/CS2040S t/123`

### Expected output
An error message informing me that the tag is invalid.

### Actual output
The command is accepted and tag is set.

### Other details
The invalid command format message for the `add` command is as follows:
```
Invalid command format! 
add: Adds a module to the module tracker. 
Parameters: n/MODULE_NAME t/TAG (Lecture, Tutorial, Lab) [e/TIMESLOT] [a/VENUE] [c/RESOURCE] [s/TEACHER] [d/DEADLINES] [r/REMARKS]
Example: add n/CS1101S t/Lecture e/210323 10:00a/COM1 
```

Referring to the `t/TAG (Lecture, Tutorial, Lab)` section, this seems to imply that the tag can only be of the following values: `Lecture`, `Tutorial`,  or `Lab`.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: hingen/ped#11

**Comment by jayhee3** [comment]
Fixed.
