### ISSUE TITLE
[PE-D][Tester B] Inconsistency in naming address and venue 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-1/tp#130]
![image.png](https://raw.githubusercontent.com/KSunil2001/ped/main/files/9b8c64a4-061e-4ad6-9bad-4492b7b31861.png)

![image.png](https://raw.githubusercontent.com/KSunil2001/ped/main/files/9a2303db-692a-47c2-8f23-bcba1a26833d.png)

The highlighted portion of the first screenshot shows "[a/ADDRESS]" and for the second screenshot it shows "[a/VENUE]". I would recommend standardizing the name to either ADDRESS or VENUE.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: KSunil2001/ped#9

**Comment by jayhee3** [comment]
Fixed.
